#!/bin/sh

/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys


echo "Creating a few devices"
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

echo "Setting up basic environment"
busybox --install -s

echo 'IP Configuration!'
ifconfig eth0 192.168.0.101 up
/bin/sh
